name: My first workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My first GitHub actions job"

            - name: List files
              run: ls -lhtr
            
            - name: Read file
              run: toutch README.md